name: Release Workflow

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  summarize-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update production branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin master
          git checkout master
          # Use PAT for authentication
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git master:production -f
